version: '3.4'

services:
  app:
    build:
      context: .
    command: npm run serve
    ports:
      - 8080:8080
    volumes:
    - ./:/usr/src/app
    - node_modules:/usr/src/app/node_modules/

volumes:
  node_modules: